spring:
########################################################
### THYMELEAF
########################################################
  thymeleaf:
    cache: false
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: HTML5
#    encoding: UTF-8
#    content-type: text/html
  datasource:
    url: jdbc:mysql://localhost:3306/wcms
    username: lm
    password: lmfr900223
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080
  servlet:
    path: /wcms
